node (){
	stage('check out source file'){
		checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanCheckout']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '29c5acc6-157e-4c98-9e62-12477be1591e', url: 'git@github.com:StevenCur30/JenkinsTest.git']]])
	}
	stage("build source file"){
		sh "cd springboot && mvn clean package -DskipTests"		
	}
}